---
- name: Install bind bind-utils
  hosts: dns_secondary
  become: true
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - bind-utils
        - bind
    
    - name: Copy named.conf file
      copy:
        src: conf_secondary.j2
        dest: /etc/named.conf

    - name: Configure DNS Servers
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'

    - name: Disable SELinux temporarily (until next reboot)
      selinux:
        policy: targeted
        state: disabled

    - name: Set SELinux state to permissive in the current session
      command: setenforce 0
      ignore_errors: yes

    - name: Add TCP port 53 to Firewalld
      ansible.builtin.command: firewall-cmd --permanent --add-port=53/tcp
      async: 600
      poll: 0
      ignore_errors: yes  # To ignore errors if the rule already exists
      become: yes

    - name: Add UDP port 53 to Firewalld
      ansible.builtin.command: firewall-cmd --permanent --add-port=53/udp
      async: 600
      poll: 0
      ignore_errors: yes  # To ignore errors if the rule already exists
      become: yes

    - name: Reload Firewalld
      ansible.builtin.command: firewall-cmd --reload
      async: 600
      poll: 0
      become: yes

    - name: Start named service
      service:
        name: named
        state: started
        enabled: yes

