---
- name: Remove Docker
  gather_facts: No
  hosts: docker dworkers
  become: yes
  
  tasks:
  - name: Remove docker if installed from CentOS repo
    yum:
      name: "{{ item }}"
      state: removed

    with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

- name: Install docker
  gather_facts: No
  hosts: docker dworkers

  tasks:
  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest 
    become: yes 

  - name: Install device-mapper-persistent-data
    yum:
      name: device-mapper-persistent-data
      state: latest
    become: yes
 
  - name: Install lvm2
    yum:
      name: lvm2
      state: latest
    become: yes

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: yes

  - name: Enable Docker Edge repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: 0
    become: yes

  - name: Enable Docker Test repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-test'
      option: enabled
      value: 0
    become: yes

  - name: Install Docker
    package:
      name: docker-ce
      state: latest
    become: yes

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
    become: yes

  - name: Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
    become: yes
