---
- name: Disable SELinux
  hosts: ldap_clients
  become: yes
  tasks:
    - name: Set SELinux to disabled
      lineinfile:
        path: /etc/sysconfig/selinux
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'

    - name: Install required packages
      yum:
        name:
          - openldap-clients
          - nss-pam-ldapd
          - authconfig
        state: latest

    - name: Configure LDAP Authentication
      command: authconfig --enableldap --enableldapauth --ldapserver=ldap-24.ziyotek.local --ldapbasedn=dc=ziyotek,dc=local --update

    - name: Enable mkhomedir and update configuration
      command: authconfig --enablemkhomedir --update

    - name: Get user information using getent
      shell: getent passwd testgui
      register: user_info_output

    - name: Display user information
      debug:
        var: user_info_output.stdout_lines
