---
- name: Install and Configure Chrony Clients
  hosts: chrony_clients
  become: yes

  vars:
    ntp_servers:
      - 192.168.0.10
      - 192.168.0.11

  tasks:
    - name: Install Chrony
      yum:
        name: chrony
        state: latest

    - name: Enable and Start Chrony Service
      systemd:
        name: chronyd
        enabled: yes
        state: started
                             
    - name: Configure Chrony Servers
      copy:
        src: chrony_clients.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Chrony Service
      systemd:
        name: chronyd
        state: restarted
