---
- name: Disable SSH Root Login
  hosts: all
  become: yes

  tasks:
    - name: Update SSH Configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin yes'
        line: 'PermitRootLogin no'
      notify: Restart SSH Service

  handlers:
    - name: Restart SSH Service
      systemd:
        name: sshd
        state: restarted
